name: Deploy with devopsellence
description: Build, push, and deploy your app using devopsellence
inputs:
  token:
    description: devopsellence API token
    required: true
runs:
  using: docker
  image: docker://ghcr.io/devopsellence/deploy-action:latest
  env:
    DEVOPSELLENCE_TOKEN: ${{ inputs.token }}
  args:
    - deploy
    - --non-interactive
